"""Add manufacturers table

Revision ID: 108f6497e3dc
Revises: 
Create Date: 2026-08-31 13:51:56.360495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '108f6497e3dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('v_status_type')
    op.drop_table('menu_metadata')
    op.drop_table('v_string_type')
    op.drop_table('v_date_type')
    with op.batch_alter_table('column_value_mappings', schema=None) as batch_op:
        batch_op.alter_column('column_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('column_value_mappings_column_id_value_key_key', type_='unique')
        batch_op.create_unique_constraint('uq_column_value', ['column_id', 'value_key'])

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('table_columns_table_id_column_key_key', type_='unique')
        batch_op.create_unique_constraint('uq_table_column', ['table_id', 'column_key'])

    with op.batch_alter_table('user_table_settings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.drop_constraint('user_table_settings_user_id_table_id_key', type_='unique')
        batch_op.create_unique_constraint('uq_user_table', ['user_id', 'table_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_table', type_='unique')
        batch_op.create_unique_constraint('user_table_settings_user_id_table_id_key', ['user_id', 'table_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.drop_constraint('uq_table_column', type_='unique')
        batch_op.create_unique_constraint('table_columns_table_id_column_key_key', ['table_id', 'column_key'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))

    with op.batch_alter_table('column_value_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_column_value', type_='unique')
        batch_op.create_unique_constraint('column_value_mappings_column_id_value_key_key', ['column_id', 'value_key'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('column_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('v_date_type',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('v_string_type',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('menu_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='menu_metadata_pkey')
    )
    op.create_table('v_status_type',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
