"""v2: add validation_rules table

Revision ID: 17be8c17c38e
Revises: 8a08c61d3e0e
Create Date: 2026-10-02 15:16:49.785158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17be8c17c38e'
down_revision = '8a08c61d3e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_rules',
    sa.Column('table_key', sa.String(length=100), nullable=False),
    sa.Column('column_key', sa.String(length=100), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_params', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_rules_column_key'), ['column_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_rules_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_validation_rules_table_column', ['table_key', 'column_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_rules_table_key'), ['table_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_rules_table_key'))
        batch_op.drop_index('ix_validation_rules_table_column')
        batch_op.drop_index(batch_op.f('ix_validation_rules_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_validation_rules_column_key'))

    op.drop_table('validation_rules')
    # ### end Alembic commands ###
