"""v2: new fields

Revision ID: d2079192deac
Revises: 
Create Date: 2026-09-28 16:41:02.943014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2079192deac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('min_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_align_h', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_align_v', sa.String(length=20), nullable=True))

    with op.batch_alter_table('column_value_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_icon', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_in_filter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('row_styles', sa.JSON(), nullable=True))

    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('min_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_width_px', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('align_h', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('align_v', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_lines', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cell_styles', sa.JSON(), nullable=True))

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_sort_list', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('default_filters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('default_filters')
        batch_op.drop_column('default_sort_list')

    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.drop_column('cell_styles')
        batch_op.drop_column('max_lines')
        batch_op.drop_column('align_v')
        batch_op.drop_column('align_h')
        batch_op.drop_column('max_width_px')
        batch_op.drop_column('min_width_px')
        batch_op.drop_column('default_width_px')

    with op.batch_alter_table('column_value_mappings', schema=None) as batch_op:
        batch_op.drop_column('row_styles')
        batch_op.drop_column('show_in_filter')
        batch_op.drop_column('show_icon')

    with op.batch_alter_table('column_types', schema=None) as batch_op:
        batch_op.drop_column('default_align_v')
        batch_op.drop_column('default_align_h')
        batch_op.drop_column('max_width_px')
        batch_op.drop_column('min_width_px')
        batch_op.drop_column('default_width_px')

    # ### end Alembic commands ###
